Initialize `theme` in localStorage if unset
dshoreman/servidor pull request #290
Opened 2020-10-13 14:40 UTC by stoppert

Inside the mixinx created hook we can check if the currentTheme is null (not set in localStorage) and then set it to the default value of 'light'

To my understanding this should always work as data should be fully initialized and reactive when the "created" hook is called.

Fixes #289

2020-10-13 19:21 UTC, dshoreman requested changes
Thanks! Good idea to use the created hook, much better than faffing about with global page/component events :laughing: 

Once travis is happy this'll be good to go. It stops at the first error so my second comment is a guess, but run `make kitchen-sink` from the project dir and it'll go through all the tests and linting bits to save having to commit/push/commit/etc

2020-10-13 19:21 UTC, dshoreman commented on resources/js/plugins/darkmode/index.js
> +                if (this.currentTheme === null) {
This should be `null === this.currentTheme`, travis is blocking merge currently

2020-10-13 19:21 UTC, dshoreman commented on resources/js/plugins/darkmode/index.js
> +                    localStorage.setItem('theme', this.currentTheme = 'light');
Suspect `this.currentTheme = 'light'` will cause errors too and needs to be defined separately on the line above

2020-10-14 05:22 UTC, stoppert commented
How rude of travis

2020-10-20 20:56 UTC, dshoreman approved these changes
Perfect! Just tested locally and the light bulb even works as expected if I delete the `theme` key from local storage before I toggle the theme. Sorry it took so long to get back to this, will get it merged now :+1:

2020-10-20 21:07 UTC, merged